import * as vscode from 'vscode';
import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

const PYTHON_API_URL = 'http://localhost:8000';

interface FileDiff {
  filename: string;
  diff: string;
  context: string;
}

// ─── Global State ────────────────────────────────────────────────────────────
let quizServer: http.Server | null = null;
const PORT = 54321;
const TIMER_SECONDS = 60;

// ─── ACTIVATE ────────────────────────────────────────────────────────────────
export function activate(context: vscode.ExtensionContext) {
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
  if (!workspaceRoot) {
    vscode.window.showErrorMessage('GateKeeper: No workspace folder found.');
    return;
  }

  startQuizServer(workspaceRoot);
  installGitHook(workspaceRoot, 'pre-push');
  vscode.window.showInformationMessage('🔒 GateKeeper is active! Pre-push quiz enabled.');
}

// ─── DEACTIVATE ───────────────────────────────────────────────────────────────
export function deactivate() {
  quizServer?.close();
}

// ─── LOCAL HTTP SERVER ────────────────────────────────────────────────────────
function startQuizServer(workspaceRoot: string) {
  quizServer = http.createServer((req, res) => {
    if (req.url === '/trigger-quiz' && req.method === 'GET') {
      const diff = getStagedDiff(workspaceRoot);

      if (!diff) {
        res.writeHead(200);
        res.end('PASS:No code changes detected — push allowed.');
        return;
      }

      triggerQuiz(diff, workspaceRoot)
        .then(({ passed, message }) => { res.writeHead(200); res.end(`${passed ? 'PASS' : 'FAIL'}:${message}`); })
        .catch(() => { res.writeHead(200); res.end('FAIL:Extension error — push blocked.'); });
    } else {
      res.writeHead(404);
      res.end('Not found');
    }
  });

  quizServer.listen(PORT, '127.0.0.1', () => {
    console.log(`GateKeeper server listening on port ${PORT}`);
  });

  quizServer.on('error', err => {
    vscode.window.showErrorMessage(`GateKeeper: Server error - ${err.message}`);
  });
}

// ─── INSTALL GIT HOOK ─────────────────────────────────────────────────────────
function installGitHook(workspaceRoot: string, hookName: 'pre-commit' | 'pre-push') {
  const hooksDir = path.join(workspaceRoot, '.git', 'hooks');
  const hookPath = path.join(hooksDir, hookName);

  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // max-time 90 = 60s quiz + ~30s buffer for question generation and grading
  const hookScript = `#!/bin/sh
# GateKeeper Hook - Auto-generated by the GateKeeper VS Code extension
# Do not edit manually.

RESPONSE=$(curl -s --max-time 90 http://127.0.0.1:${PORT}/trigger-quiz)
STATUS=$(echo "$RESPONSE" | cut -d: -f1)
MESSAGE=$(echo "$RESPONSE" | cut -d: -f2-)

if [ "$STATUS" = "PASS" ]; then
  echo "✅ GateKeeper: $MESSAGE"
  exit 0
else
  echo "❌ GateKeeper: $MESSAGE"
  exit 1
fi
`;

  fs.writeFileSync(hookPath, hookScript, { mode: 0o755 });
  console.log(`GateKeeper: ${hookName} hook installed at ${hookPath}`);
}

// ─── GET PUSH DIFF ───────────────────────────────────────────────────────────
function getStagedDiff(workspaceRoot: string): string {
  try {
    // -W: full function context so AI sees the whole picture
    // -w: ignore whitespace-only changes (linter/formatter runs)
    // @{u}...HEAD: aggregate diff of everything being pushed vs upstream
    return execSync('git diff -w -W @{u}...HEAD', { cwd: workspaceRoot }).toString().trim();
  } catch {
    // No upstream set yet (first push) — fall back to staged changes
    try {
      return execSync('git diff -w -W --cached', { cwd: workspaceRoot }).toString().trim();
    } catch (err) {
      console.error('GateKeeper: Failed to get diff', err);
      return '';
    }
  }
}

// ─── TRIGGER QUIZ ─────────────────────────────────────────────────────────────
function triggerQuiz(diff: string, workspaceRoot: string): Promise<{passed: boolean, message: string}> {
  return new Promise(async (resolve) => {
    vscode.window.showInformationMessage('🔒 GateKeeper: Checking your push...');
    const quizData = await generateQuestion(diff, workspaceRoot);

    // Backend returned an early PASS (trust level, diff too large, etc.) — no quiz needed
    if (quizData === null) {
      resolve({ passed: true, message: 'Trust level passed — no quiz needed.' });
      return;
    }

    const { question, quiz_id, user_id } = quizData;

    const panel = vscode.window.createWebviewPanel(
      'gatekeeperQuiz',
      '🔒 GateKeeper: Pop Quiz',
      vscode.ViewColumn.One,
      { enableScripts: true, retainContextWhenHidden: true }
    );

    panel.webview.html = getWebviewContent(question, diff);

    // ── THE FIX: this flag prevents onDidDispose from overriding resolve() ───
    let answered = false;

    panel.webview.onDidReceiveMessage(async (msg) => {
      if (msg.command === 'security-violation' && !answered) {
        answered = true;
        panel.dispose();
        vscode.window.showErrorMessage(
          '🚫 GateKeeper: Commit blocked — focus violation detected. Do not switch windows or tabs during the quiz.'
        );
        resolve({ passed: false, message: 'Focus violation — push blocked.' });
        return;
      }

      if (msg.command === 'submit' && !answered) {
        answered = true; // set BEFORE the async call so onDidDispose can't race

        vscode.window.showInformationMessage('🔒 GateKeeper: Checking your answer...');
        const passed = await checkAnswer(quiz_id, user_id, msg.text ?? '');

        panel.dispose(); // triggers onDidDispose, but answered=true so it's a no-op

        if (passed) {
          vscode.window.showInformationMessage('✅ GateKeeper: Correct! Commit allowed.');
          resolve({ passed: true, message: 'Correct answer — push allowed.' });
        } else {
          vscode.window.showErrorMessage('❌ GateKeeper: Wrong answer. Commit blocked!');
          resolve({ passed: false, message: 'Wrong answer — push blocked.' });
        }
      }
    });

    // Only fires if user closes the panel WITHOUT answering
    panel.onDidDispose(() => {
      if (!answered) {
        resolve({ passed: false, message: 'Quiz closed without answering — push blocked.' });
      }
    });
  });
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────
function getGitUser(workspaceRoot: string): string {
  try {
    return execSync('git config user.email', { cwd: workspaceRoot }).toString().trim();
  } catch {
    return 'unknown';
  }
}

function getCommitHash(workspaceRoot: string): string {
  try {
    return execSync('git rev-parse --short HEAD', { cwd: workspaceRoot }).toString().trim();
  } catch {
    return Date.now().toString(16);
  }
}

function parseDiff(rawDiff: string, workspaceRoot: string): { files: FileDiff[], total_diff_size: number } {
  const ignorePath = path.join(workspaceRoot, '.gatekeeperignore');
  const ignored = fs.existsSync(ignorePath)
    ? fs.readFileSync(ignorePath, 'utf8').split('\n').map(l => l.trim()).filter(Boolean)
    : [];

  const sections = rawDiff.split(/^diff --git /m).filter(Boolean);
  const files: FileDiff[] = [];
  let total_diff_size = 0;

  for (const section of sections) {
    const match = section.match(/\+\+\+ b\/(.+)/);
    if (!match) { continue; }
    const filename = match[1].trim();
    if (ignored.some((pattern: string) => filename.includes(pattern))) { continue; }

    const diffStart = section.indexOf('@@');
    if (diffStart === -1) { continue; }

    const diff = section.slice(diffStart);
    total_diff_size += diff.split('\n').filter((l: string) => l.startsWith('+') || l.startsWith('-')).length;
    files.push({ filename, diff, context: '' });
  }

  return { files, total_diff_size };
}

// ─── API: GENERATE QUESTION ───────────────────────────────────────────────────
async function generateQuestion(diff: string, workspaceRoot: string): Promise<{ question: string, quiz_id: string, user_id: string, reason?: string } | null> {
  const { files, total_diff_size } = parseDiff(diff, workspaceRoot);
  const user_id = getGitUser(workspaceRoot);
  const commit_hash = getCommitHash(workspaceRoot);

  try {
    const response = await fetch(`${PYTHON_API_URL}/api/check-push`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ user_id, commit_hash, total_diff_size, files })
    });

    if (!response.ok) { throw new Error(`API ${response.status}`); }

    const data = await response.json() as { action: string, question?: string, quiz_id?: string, message?: string, reason?: string };

    if (data.action === 'PASS') { return null; }

    return { question: data.question ?? '', quiz_id: data.quiz_id ?? '', user_id, reason: data.reason };
  } catch (err) {
    console.error('GateKeeper: check-push failed', err);
    return { question: 'Backend unreachable. What does this commit do?', quiz_id: '', user_id };
  }
}

// ─── API: CHECK ANSWER ────────────────────────────────────────────────────────
async function checkAnswer(quiz_id: string, user_id: string, answer: string): Promise<boolean> {
  if (!answer || answer.trim() === '') { return false; }

  try {
    const response = await fetch(`${PYTHON_API_URL}/api/submit-answer`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ user_id, quiz_id, user_answer: answer })
    });

    if (!response.ok) { throw new Error(`API ${response.status}`); }

    const data = await response.json() as { status: string };
    return data.status === 'PASS';
  } catch (err) {
    console.error('GateKeeper: submit-answer failed', err);
    return answer.trim().length >= 20;
  }
}

// ─── WEBVIEW HTML ─────────────────────────────────────────────────────────────
function getWebviewContent(question: string, diff: string): string {
  const preview = diff.split('\n').slice(0, 30).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>GateKeeper Quiz</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #1e1e2e;
      color: #cdd6f4;
      padding: 32px;
      min-height: 100vh;
      /* Disable text selection everywhere except the textarea */
      user-select: none;
      -webkit-user-select: none;
    }
    textarea { user-select: text; -webkit-user-select: text; }

    .header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 20px;
    }
    .header h1 { font-size: 22px; font-weight: 700; color: #cba6f7; }
    .badge {
      background: #f38ba8;
      color: #1e1e2e;
      font-size: 11px;
      font-weight: 700;
      padding: 3px 8px;
      border-radius: 99px;
      letter-spacing: 0.5px;
    }
    .badge-security {
      background: #cba6f7;
      color: #1e1e2e;
    }

    /* ── Timer ── */
    .timer-row {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 20px;
    }
    .timer-label { font-size: 13px; color: #6c7086; white-space: nowrap; }
    #timer-display {
      font-size: 20px;
      font-weight: 800;
      color: #a6e3a1;
      font-variant-numeric: tabular-nums;
      min-width: 44px;
    }
    #timer-display.warning { color: #fab387; }
    #timer-display.danger  { color: #f38ba8; animation: pulse 0.5s infinite alternate; }
    @keyframes pulse { from { opacity: 1; } to { opacity: 0.5; } }
    .timer-bar-bg {
      flex: 1;
      height: 6px;
      background: #45475a;
      border-radius: 99px;
      overflow: hidden;
    }
    #timer-bar {
      height: 100%;
      background: #a6e3a1;
      border-radius: 99px;
      width: 100%;
      transition: width 1s linear, background 0.5s;
    }

    /* ── Anti-cheat banner ── */
    #anticheat-banner {
      display: none;
      background: #f38ba8;
      color: #1e1e2e;
      padding: 10px 16px;
      border-radius: 8px;
      font-weight: 700;
      font-size: 13px;
      margin-bottom: 16px;
    }

    .card {
      background: #313244;
      border-radius: 12px;
      padding: 20px 24px;
      margin-bottom: 20px;
      border: 1px solid #45475a;
    }
    .card-label {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: #6c7086;
      margin-bottom: 10px;
    }
    .question-text { font-size: 16px; line-height: 1.6; color: #cdd6f4; }
    .code-preview {
      background: #1e1e2e;
      border-radius: 8px;
      padding: 14px;
      font-family: 'JetBrains Mono', 'Fira Code', monospace;
      font-size: 12px;
      line-height: 1.6;
      color: #a6e3a1;
      white-space: pre-wrap;
      overflow-x: auto;
      border: 1px solid #45475a;
      max-height: 180px;
      overflow-y: auto;
    }
    textarea {
      width: 100%;
      background: #1e1e2e;
      border: 1px solid #45475a;
      border-radius: 8px;
      color: #cdd6f4;
      font-size: 14px;
      padding: 14px;
      resize: vertical;
      min-height: 100px;
      outline: none;
      font-family: inherit;
      transition: border-color 0.2s;
    }
    textarea:focus { border-color: #cba6f7; }
    .actions { display: flex; gap: 12px; margin-top: 20px; }
    button {
      padding: 10px 24px;
      border-radius: 8px;
      border: none;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      transition: opacity 0.2s;
    }
    button:hover { opacity: 0.85; }
    button:disabled { opacity: 0.4; cursor: not-allowed; }
    .btn-submit { background: #cba6f7; color: #1e1e2e; flex: 1; }
    .btn-skip   { background: #45475a; color: #cdd6f4; }
    .hint { font-size: 12px; color: #f38ba8; margin-top: 10px; }
  </style>
</head>
<body>

  <div class="header">
    <h1>🔒 GateKeeper</h1>
    <span class="badge">PRE-COMMIT</span>
    <span class="badge badge-security">SECURITY LEVEL: HIGH</span>
  </div>

  <div id="anticheat-banner">🚫 Security violation: focus lost — commit blocked!</div>

  <div class="timer-row">
    <span class="timer-label">Time remaining:</span>
    <span id="timer-display">${TIMER_SECONDS}s</span>
    <div class="timer-bar-bg"><div id="timer-bar"></div></div>
  </div>

  <div class="card">
    <div class="card-label">📄 Staged diff (preview)</div>
    <pre class="code-preview">${escapeHtml(preview)}</pre>
  </div>

  <div class="card">
    <div class="card-label">❓ Quiz Question</div>
    <p class="question-text">${escapeHtml(question)}</p>
  </div>

  <div class="card">
    <div class="card-label">✏️ Your Answer</div>
    <textarea id="answer" placeholder="Type your answer here..." autocomplete="off" spellcheck="false"></textarea>
    <p class="hint">⚠️ Commit blocked if you skip or answer incorrectly. Copy-paste is disabled.</p>
  </div>

  <div class="actions">
    <button class="btn-submit" id="btn-submit" onclick="submitAnswer()">Submit Answer ✅</button>
    <button class="btn-skip" onclick="skipQuiz()">Skip (Block Commit) ❌</button>
  </div>

  <script>
    const vscode = acquireVsCodeApi();
    const TOTAL = ${TIMER_SECONDS};
    let remaining = TOTAL;
    let submitted = false;

    const display  = document.getElementById('timer-display');
    const bar      = document.getElementById('timer-bar');
    const textarea = document.getElementById('answer');
    const btnSubmit = document.getElementById('btn-submit');

    // ── Timer ──────────────────────────────────────────────────────────────────
    function tick() {
      if (submitted) { return; }
      remaining = Math.max(0, remaining - 1);

      display.textContent = remaining + 's';
      bar.style.width = (remaining / TOTAL * 100) + '%';

      if (remaining <= 10) {
        display.className = 'danger';
        bar.style.background = '#f38ba8';
      } else if (remaining <= 20) {
        display.className = 'warning';
        bar.style.background = '#fab387';
      }

      if (remaining <= 0) { autoFail(); }
    }

    const timerInterval = setInterval(tick, 1000);

    function autoFail() {
      if (submitted) { return; }
      submitted = true;
      clearInterval(timerInterval);
      btnSubmit.disabled = true;
      display.textContent = '0s';
      vscode.postMessage({ command: 'submit', text: '' });
    }

    // ── Anti-cheat: no copy / cut / paste ────────────────────────────────────
    document.addEventListener('copy',  e => e.preventDefault());
    document.addEventListener('cut',   e => e.preventDefault());
    document.addEventListener('paste', e => e.preventDefault());

    // ── Anti-cheat: no right-click context menu ───────────────────────────────
    document.addEventListener('contextmenu', e => e.preventDefault());

    // ── Anti-cheat: no drag and drop ─────────────────────────────────────────
    document.addEventListener('dragover', e => e.preventDefault());
    document.addEventListener('drop',     e => e.preventDefault());

    // ── Strict Focus: any focus loss → immediate hard fail ───────────────────
    window.addEventListener('blur', () => {
      if (!submitted) {
        submitted = true;
        clearInterval(timerInterval);
        btnSubmit.disabled = true;
        const banner = document.getElementById('anticheat-banner');
        banner.style.display = 'block';
        vscode.postMessage({ command: 'security-violation', reason: 'Focus lost' });
      }
    });

    // ── Anti-cheat: block keyboard shortcuts used for opening DevTools / new tabs
    document.addEventListener('keydown', e => {
      const forbidden =
        (e.key === 'F12') ||
        (e.ctrlKey && e.shiftKey && ['I','J','C'].includes(e.key)) ||
        (e.metaKey && e.shiftKey && ['I','J','C'].includes(e.key)) ||
        (e.ctrlKey && e.key === 'u') ||
        (e.metaKey && e.key === 'u');
      if (forbidden) { e.preventDefault(); }
    });

    // ── Submit ────────────────────────────────────────────────────────────────
    function submitAnswer() {
      if (submitted) { return; }
      const answer = textarea.value.trim();
      if (!answer) {
        alert('Please write an answer before submitting!');
        return;
      }
      submitted = true;
      clearInterval(timerInterval);
      btnSubmit.disabled = true;
      vscode.postMessage({ command: 'submit', text: answer });
    }

    function skipQuiz() {
      if (submitted) { return; }
      submitted = true;
      clearInterval(timerInterval);
      btnSubmit.disabled = true;
      vscode.postMessage({ command: 'submit', text: '' });
    }

    // Focus the textarea immediately
    textarea.focus();
  </script>
</body>
</html>`;
}

// ─── HELPER: Escape HTML special characters ───────────────────────────────────
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}