import * as vscode from 'vscode';
import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

// ─── Global State ────────────────────────────────────────────────────────────
let quizServer: http.Server | null = null;
const PORT = 54321;
const TIMER_SECONDS = 60;

// ─── ACTIVATE ────────────────────────────────────────────────────────────────
export function activate(context: vscode.ExtensionContext) {
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
  if (!workspaceRoot) {
    vscode.window.showErrorMessage('GateKeeper: No workspace folder found.');
    return;
  }

  startQuizServer(workspaceRoot);
  installGitHook(workspaceRoot, 'pre-commit');
  vscode.window.showInformationMessage('🔒 GateKeeper is active! Pre-commit quiz enabled.');
}

// ─── DEACTIVATE ───────────────────────────────────────────────────────────────
export function deactivate() {
  quizServer?.close();
}

// ─── LOCAL HTTP SERVER ────────────────────────────────────────────────────────
function startQuizServer(workspaceRoot: string) {
  quizServer = http.createServer((req, res) => {
    if (req.url === '/trigger-quiz' && req.method === 'GET') {
      const diff = getStagedDiff(workspaceRoot);

      if (!diff) {
        res.writeHead(200);
        res.end('0');
        return;
      }

      triggerQuiz(diff)
        .then(passed => { res.writeHead(200); res.end(passed ? '0' : '1'); })
        .catch(() => { res.writeHead(200); res.end('1'); });
    } else {
      res.writeHead(404);
      res.end('Not found');
    }
  });

  quizServer.listen(PORT, '127.0.0.1', () => {
    console.log(`GateKeeper server listening on port ${PORT}`);
  });

  quizServer.on('error', err => {
    vscode.window.showErrorMessage(`GateKeeper: Server error - ${err.message}`);
  });
}

// ─── INSTALL GIT HOOK ─────────────────────────────────────────────────────────
function installGitHook(workspaceRoot: string, hookName: 'pre-commit' | 'pre-push') {
  const hooksDir = path.join(workspaceRoot, '.git', 'hooks');
  const hookPath = path.join(hooksDir, hookName);

  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // max-time 90 = 60s quiz + ~30s buffer for question generation and grading
  const hookScript = `#!/bin/sh
# GateKeeper Hook - Auto-generated by the GateKeeper VS Code extension
# Do not edit manually.

RESPONSE=$(curl -s --max-time 90 http://127.0.0.1:${PORT}/trigger-quiz)

if [ "$RESPONSE" = "0" ]; then
  exit 0
else
  echo "❌ GateKeeper: Quiz failed or not answered. Commit blocked."
  exit 1
fi
`;

  fs.writeFileSync(hookPath, hookScript, { mode: 0o755 });
  console.log(`GateKeeper: ${hookName} hook installed at ${hookPath}`);
}

// ─── GET STAGED DIFF ─────────────────────────────────────────────────────────
function getStagedDiff(workspaceRoot: string): string {
  try {
    return execSync('git diff --cached', { cwd: workspaceRoot }).toString().trim();
  } catch (err) {
    console.error('GateKeeper: Failed to get staged diff', err);
    return '';
  }
}

// ─── TRIGGER QUIZ ─────────────────────────────────────────────────────────────
function triggerQuiz(diff: string): Promise<boolean> {
  return new Promise(async (resolve) => {
    vscode.window.showInformationMessage('🔒 GateKeeper: Generating quiz question...');
    const question = await generateQuestion(diff);

    const panel = vscode.window.createWebviewPanel(
      'gatekeeperQuiz',
      '🔒 GateKeeper: Pop Quiz',
      vscode.ViewColumn.One,
      { enableScripts: true, retainContextWhenHidden: true }
    );

    panel.webview.html = getWebviewContent(question, diff);

    // ── THE FIX: this flag prevents onDidDispose from overriding resolve() ───
    let answered = false;

    panel.webview.onDidReceiveMessage(async (msg) => {
      if (msg.command === 'submit' && !answered) {
        answered = true; // set BEFORE the async call so onDidDispose can't race

        vscode.window.showInformationMessage('🔒 GateKeeper: Checking your answer...');
        const passed = await checkAnswer(question, msg.text ?? '', diff);

        panel.dispose(); // triggers onDidDispose, but answered=true so it's a no-op

        if (passed) {
          vscode.window.showInformationMessage('✅ GateKeeper: Correct! Commit allowed.');
        } else {
          vscode.window.showErrorMessage('❌ GateKeeper: Wrong answer. Commit blocked!');
        }

        resolve(passed);
      }
    });

    // Only fires if user closes the panel WITHOUT answering
    panel.onDidDispose(() => {
      if (!answered) {
        resolve(false);
      }
    });
  });
}

// ─── AI: GENERATE QUESTION ────────────────────────────────────────────────────
async function generateQuestion(diff: string): Promise<string> {
  // TODO: Replace with POST /api/check-push once the Python backend is ready.
  // The backend will receive the diff and return { action: "INTERROGATE", question: "..." }
  return `What is the purpose of the changes you just staged? Explain the specific logic you added or modified and why you made that decision.`;
}

// ─── AI: CHECK ANSWER ─────────────────────────────────────────────────────────
async function checkAnswer(question: string, answer: string, diff: string): Promise<boolean> {
  // TODO: Replace with POST /api/submit-answer once the Python backend is ready.
  // The backend will return { status: "PASS" | "FAIL", explanation: "..." }

  // Empty answer = timer expired or skipped → always fail
  if (!answer || answer.trim() === '') {
    return false;
  }

  // Placeholder: pass if the answer is substantive (at least 20 chars)
  return answer.trim().length >= 20;
}

// ─── WEBVIEW HTML ─────────────────────────────────────────────────────────────
function getWebviewContent(question: string, diff: string): string {
  const preview = diff.split('\n').slice(0, 30).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>GateKeeper Quiz</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #1e1e2e;
      color: #cdd6f4;
      padding: 32px;
      min-height: 100vh;
      /* Disable text selection everywhere except the textarea */
      user-select: none;
      -webkit-user-select: none;
    }
    textarea { user-select: text; -webkit-user-select: text; }

    .header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 20px;
    }
    .header h1 { font-size: 22px; font-weight: 700; color: #cba6f7; }
    .badge {
      background: #f38ba8;
      color: #1e1e2e;
      font-size: 11px;
      font-weight: 700;
      padding: 3px 8px;
      border-radius: 99px;
      letter-spacing: 0.5px;
    }

    /* ── Timer ── */
    .timer-row {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 20px;
    }
    .timer-label { font-size: 13px; color: #6c7086; white-space: nowrap; }
    #timer-display {
      font-size: 20px;
      font-weight: 800;
      color: #a6e3a1;
      font-variant-numeric: tabular-nums;
      min-width: 44px;
    }
    #timer-display.warning { color: #fab387; }
    #timer-display.danger  { color: #f38ba8; animation: pulse 0.5s infinite alternate; }
    @keyframes pulse { from { opacity: 1; } to { opacity: 0.5; } }
    .timer-bar-bg {
      flex: 1;
      height: 6px;
      background: #45475a;
      border-radius: 99px;
      overflow: hidden;
    }
    #timer-bar {
      height: 100%;
      background: #a6e3a1;
      border-radius: 99px;
      width: 100%;
      transition: width 1s linear, background 0.5s;
    }

    /* ── Anti-cheat banner ── */
    #anticheat-banner {
      display: none;
      background: #f38ba8;
      color: #1e1e2e;
      padding: 10px 16px;
      border-radius: 8px;
      font-weight: 700;
      font-size: 13px;
      margin-bottom: 16px;
    }

    .card {
      background: #313244;
      border-radius: 12px;
      padding: 20px 24px;
      margin-bottom: 20px;
      border: 1px solid #45475a;
    }
    .card-label {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: #6c7086;
      margin-bottom: 10px;
    }
    .question-text { font-size: 16px; line-height: 1.6; color: #cdd6f4; }
    .code-preview {
      background: #1e1e2e;
      border-radius: 8px;
      padding: 14px;
      font-family: 'JetBrains Mono', 'Fira Code', monospace;
      font-size: 12px;
      line-height: 1.6;
      color: #a6e3a1;
      white-space: pre-wrap;
      overflow-x: auto;
      border: 1px solid #45475a;
      max-height: 180px;
      overflow-y: auto;
    }
    textarea {
      width: 100%;
      background: #1e1e2e;
      border: 1px solid #45475a;
      border-radius: 8px;
      color: #cdd6f4;
      font-size: 14px;
      padding: 14px;
      resize: vertical;
      min-height: 100px;
      outline: none;
      font-family: inherit;
      transition: border-color 0.2s;
    }
    textarea:focus { border-color: #cba6f7; }
    .actions { display: flex; gap: 12px; margin-top: 20px; }
    button {
      padding: 10px 24px;
      border-radius: 8px;
      border: none;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      transition: opacity 0.2s;
    }
    button:hover { opacity: 0.85; }
    button:disabled { opacity: 0.4; cursor: not-allowed; }
    .btn-submit { background: #cba6f7; color: #1e1e2e; flex: 1; }
    .btn-skip   { background: #45475a; color: #cdd6f4; }
    .hint { font-size: 12px; color: #f38ba8; margin-top: 10px; }
  </style>
</head>
<body>

  <div class="header">
    <h1>🔒 GateKeeper</h1>
    <span class="badge">PRE-COMMIT</span>
  </div>

  <div id="anticheat-banner">⚠️ Anti-cheat: tab switch detected — 10 seconds deducted!</div>

  <div class="timer-row">
    <span class="timer-label">Time remaining:</span>
    <span id="timer-display">${TIMER_SECONDS}s</span>
    <div class="timer-bar-bg"><div id="timer-bar"></div></div>
  </div>

  <div class="card">
    <div class="card-label">📄 Staged diff (preview)</div>
    <pre class="code-preview">${escapeHtml(preview)}</pre>
  </div>

  <div class="card">
    <div class="card-label">❓ Quiz Question</div>
    <p class="question-text">${escapeHtml(question)}</p>
  </div>

  <div class="card">
    <div class="card-label">✏️ Your Answer</div>
    <textarea id="answer" placeholder="Type your answer here..." autocomplete="off" spellcheck="false"></textarea>
    <p class="hint">⚠️ Commit blocked if you skip or answer incorrectly. Copy-paste is disabled.</p>
  </div>

  <div class="actions">
    <button class="btn-submit" id="btn-submit" onclick="submitAnswer()">Submit Answer ✅</button>
    <button class="btn-skip" onclick="skipQuiz()">Skip (Block Commit) ❌</button>
  </div>

  <script>
    const vscode = acquireVsCodeApi();
    const TOTAL = ${TIMER_SECONDS};
    let remaining = TOTAL;
    let submitted = false;

    const display  = document.getElementById('timer-display');
    const bar      = document.getElementById('timer-bar');
    const textarea = document.getElementById('answer');
    const btnSubmit = document.getElementById('btn-submit');

    // ── Timer ──────────────────────────────────────────────────────────────────
    function tick() {
      if (submitted) { return; }
      remaining = Math.max(0, remaining - 1);

      display.textContent = remaining + 's';
      bar.style.width = (remaining / TOTAL * 100) + '%';

      if (remaining <= 10) {
        display.className = 'danger';
        bar.style.background = '#f38ba8';
      } else if (remaining <= 20) {
        display.className = 'warning';
        bar.style.background = '#fab387';
      }

      if (remaining <= 0) { autoFail(); }
    }

    const timerInterval = setInterval(tick, 1000);

    function autoFail() {
      if (submitted) { return; }
      submitted = true;
      clearInterval(timerInterval);
      btnSubmit.disabled = true;
      display.textContent = '0s';
      vscode.postMessage({ command: 'submit', text: '' });
    }

    // ── Anti-cheat: no copy / cut / paste ────────────────────────────────────
    document.addEventListener('copy',  e => e.preventDefault());
    document.addEventListener('cut',   e => e.preventDefault());
    document.addEventListener('paste', e => e.preventDefault());

    // ── Anti-cheat: no right-click context menu ───────────────────────────────
    document.addEventListener('contextmenu', e => e.preventDefault());

    // ── Anti-cheat: tab / window visibility switch → deduct 10s ──────────────
    document.addEventListener('visibilitychange', () => {
      if (document.hidden && !submitted) {
        remaining = Math.max(0, remaining - 10);
        const banner = document.getElementById('anticheat-banner');
        banner.style.display = 'block';
        setTimeout(() => { banner.style.display = 'none'; }, 3000);
      }
    });

    // ── Anti-cheat: block keyboard shortcuts used for opening DevTools / new tabs
    document.addEventListener('keydown', e => {
      const forbidden =
        (e.key === 'F12') ||
        (e.ctrlKey && e.shiftKey && ['I','J','C'].includes(e.key)) ||
        (e.metaKey && e.shiftKey && ['I','J','C'].includes(e.key)) ||
        (e.ctrlKey && e.key === 'u') ||
        (e.metaKey && e.key === 'u');
      if (forbidden) { e.preventDefault(); }
    });

    // ── Submit ────────────────────────────────────────────────────────────────
    function submitAnswer() {
      if (submitted) { return; }
      const answer = textarea.value.trim();
      if (!answer) {
        alert('Please write an answer before submitting!');
        return;
      }
      submitted = true;
      clearInterval(timerInterval);
      btnSubmit.disabled = true;
      vscode.postMessage({ command: 'submit', text: answer });
    }

    function skipQuiz() {
      if (submitted) { return; }
      submitted = true;
      clearInterval(timerInterval);
      btnSubmit.disabled = true;
      vscode.postMessage({ command: 'submit', text: '' });
    }

    // Focus the textarea immediately
    textarea.focus();
  </script>
</body>
</html>`;
}

// ─── HELPER: Escape HTML special characters ───────────────────────────────────
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
